# Generated by Django 2.2 on 2019-04-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderMainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Ссылка на картинку')),
            ],
            options={
                'verbose_name': 'Ссылка на картинку',
                'verbose_name_plural': 'Ссылки на картинку',
            },
        ),
    ]
