# Generated by Django 2.2 on 2019-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_aboutus_contacts_deliveryandpayment_exchangeandreturn_howtouse_logowithphones_socialnetwork_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image_url',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/about_us'),
        ),
        migrations.AlterField(
            model_name='logowithphones',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
