# Generated by Django 2.2 on 2019-04-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190416_1345'),
    ]

    operations = [
    ]
