# Generated by Django 2.2 on 2019-05-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190417_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_domain', models.BooleanField(default=True, verbose_name='True - домен, False - поддомен')),
                ('name', models.CharField(max_length=32, verbose_name='Имя домена/поддомена')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
