# Generated by Django 2.2 on 2019-04-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190417_0721'),
    ]

    operations = [
    ]
