# Generated by Django 2.2 on 2019-04-19 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_auto_20190418_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_subdomain', models.CharField(blank=True, choices=[('DM', 'Домен'), ('SD', 'Поддомен')], max_length=2, null=True, verbose_name='Домен/поддомен')),
                ('domain_name', models.URLField(blank=True, null=True, verbose_name='Имя домена')),
                ('call_back', models.CharField(blank=True, choices=[('YES', 'Включена'), ('NO', 'Выключена')], max_length=3, null=True, verbose_name='Функция Сall-back')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('top_sales', models.BooleanField(default=False, verbose_name='Топ продаж')),
                ('no_items', models.BooleanField(default=False, verbose_name='Без товара')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='users/company_logo', verbose_name='Логотип')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSliderURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Картинка для слайдера')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_urls', to='shop.MyStore')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Раздел навигации')),
                ('store', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigations', to='shop.MyStore')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона для хедера')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_phones', to='shop.MyStore')),
            ],
        ),
        migrations.CreateModel(
            name='FooterPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона для футера')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_phones', to='shop.MyStore')),
            ],
        ),
    ]
