# Generated by Django 2.2 on 2019-04-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_footerphonenumber_headerphonenumber_mystore_navigation_storesliderurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image_url',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
