# Generated by Django 2.2 on 2019-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_feedback_productcharacteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='Лучший товар'),
        ),
    ]
