# Generated by Django 2.2 on 2019-05-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_best'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimageurl',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageurls', to='catalog.Product'),
        ),
    ]
