# Generated by Django 2.2 on 2019-04-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_feedback_productcharacteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_phone', models.CharField(max_length=13, verbose_name='Телефон покупателя')),
                ('city', models.CharField(blank=True, max_length=256, null=True, verbose_name='Город покупателя')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя покупателя')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия покупателя')),
                ('patronymic', models.CharField(blank=True, max_length=256, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронный адрес покупателя')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон покупателя')),
                ('nova_poshta', models.CharField(blank=True, max_length=256, null=True, verbose_name='Отделение новой почты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
    ]
