# Generated by Django 2.2 on 2019-04-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='Електронный адрес покупателя'),
        ),
    ]
