# Generated by Django 2.2 on 2019-05-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190412_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_phone',
        ),
    ]
