# Generated by Django 2.2 on 2019-04-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190412_1416'),
        ('orders', '0002_auto_20190418_1343'),
    ]

    operations = [
    ]
